### ISSUE TITLE
Plans for other cmp file linting?

### ISSUE THREAD

**Issue by maniax89** [forcedotcom/eslint-plugin-aura#1]
I am a big fan of this library and have already started looking to integrate it into our team's workflow for standardizing lightning component bundle javascript files (`*Helper.js`, `*Renderer.js`, `*Controller.js`)

I was curious if there is/will be any plans to implement something similar to a JSX parser for the `.cmp` files so that can be linted as well (see https://github.com/yannickcr/eslint-plugin-react for an example)? Right now I am utilizing the JSX parser for linting simple things like spacing and html attributes, but it would be fantastic to handle it properly with either an extension of JSX parsing or completely custom parsing for aura component `.cmp` files. 

It would pair well with the https://github.com/forcedotcom/eslint-plugin-visualforce along with all the other linting efforts going on for the sfdx approach to development on salesforce

**Comment by touzoku** [comment]
Hi, @maniax89!

I think it is a good idea! Feel free to start working on it or submitting an idea to the Trailblazer Community. I will be more than glad to contribute to the rules! 😄 

Currently, even `eslint-plugin-visualforce` requires some fixing, so I'm not sure when I can start working on some new tooling.

Cheers!
Marat

**Comment by trevor-bliss** [comment]
No plans that I'm aware of for linting of non-Javascript files, but if anyone in the community has developed anything I would love to see it!
