### ISSUE TITLE
Keyword 'const' is reserved

### ISSUE THREAD

**Issue by kiliw** [forcedotcom/eslint-plugin-aura#11]
What did I do:
Add ESLint with the eslint-plugin-aura to a existing codebase in order to lint the aura component js files.
```
// .eslintrc.json
{
  "plugins": [
    "@salesforce/eslint-plugin-aura"
  ],
  "extends": [
    "plugin:@salesforce/eslint-plugin-aura/recommended"
  ],
  "rules": {
    "func-names": ["error", "never"],
    "quote-props": ["error", "as-needed"],
    "no-magic-numbers": "off",
    "max-nested-callbacks": "warn",
    "camelcase": "warn",
    "lines-around-comment": ["error", {"beforeLineComment":  false}],
    "no-multiple-empty-lines": ["error",
      {
        "max": 1
      }],
    "semi": ["error", "never"]
  }
}
```
What happens:
In all the files the following error occures `error  Parsing error: The keyword 'const' is reserved`

Workaround:
add ecma version 6 to the config file
```
"parserOptions": {
    "ecmaVersion": 6
      },
```

**Comment by rochejul** [comment]
Hi @kiliw 

This is curious, I thought the usage of Aura was limited to ES5 only and if we want to use ES6, we should use then LWC?

What are your thoughts?

Many thanks

**Comment by kiliw** [comment]
Hey @rochejul ,

I think it is basically ES5 but with some ES6 features. At least for the project I'm working on right now it will not be possible to switch to LWC that fast and even then all the existing components will stay in aura format thus linting of at least the js files would be great.
I thought that this weird mixture of features is covered in the plugin settings :) But since no one else had this issue maybe I just configured it wrong?

**Comment by trevor-bliss** [comment]
The [documented support](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/js_supported_es.htm?search_text=es6) for Aura is ES5 + Promises. Updating your local configuration to support ES6 features is fine if you want to allow those, but by default this package won't support ES6.

**Comment by thesunlover** [comment]
Support for Internet Explorer ended on June 15, 2022 . why do we still care about IE and what it supports from es6?
https://support.microsoft.com/en-us/windows/use-internet-explorer-in-windows-10-7248a101-d5dd-bded-d843-d9427c42d60f
