### ISSUE TITLE
Allow usage of ESLint v7

### ISSUE THREAD

**Issue by pozil** [forcedotcom/eslint-plugin-aura#13]
Current version of `eslint-plugin-aura` has an outdated dependency on `eslint-plugin-compat@3.3.0` which doesn't support the latest major version of ESLint (v7 which is close to a year old).

This results in broken builds:
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: eslint@7.20.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^7.20.0" from the root project
npm ERR!   peer eslint@"^6 || ^7" from @salesforce/eslint-config-lwc@0.9.0
npm ERR!   node_modules/@salesforce/eslint-config-lwc
npm ERR!     dev @salesforce/eslint-config-lwc@"^0.9.0" from the root project
npm ERR!   6 more (@salesforce/eslint-plugin-aura, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0" from eslint-plugin-compat@3.3.0
npm ERR! node_modules/@salesforce/eslint-plugin-aura/node_modules/eslint-plugin-compat
npm ERR!   eslint-plugin-compat@"3.3.0" from @salesforce/eslint-plugin-aura@1.4.0
npm ERR!   node_modules/@salesforce/eslint-plugin-aura
npm ERR!     dev @salesforce/eslint-plugin-aura@"^1.4.0" from the root project
```

**Comment by pozil** [comment]
Dropping these changes as I've been told that his library is not officially supported and that we should use the `force:lightning:lint` CLI command.

**Comment by touzoku** [comment]
@pozil actually it is now officially supported, but I am not entirely sure 😓 @trevor-bliss what'd you say?

**Comment by pozil** [comment]
Yes, you're right @touzoku. There was an internal debate and the outcome was:
- this plugin is officially supported but it needs to evolve to integrate additional rules from other linting projects including the ones used by the CLI command.
- the `force:lightning:lint` CLI command will be deprecated.

I'll reopen the issue.

**Comment by trevor-bliss** [comment]
Well I wouldn't call it "officially supported" until the package is updated and someone internally who works on Aura reviews the rules, but the plan @pozil outlined above is correct for the future.
