### ISSUE TITLE
Proposal - Version 2.0.0 release tracking 

### ISSUE THREAD

**Issue by pmdartus** [forcedotcom/eslint-plugin-aura#16]
## Major changes

- Add support for ESLint v7 (#13). 
  - ESLint 7 was released more than a year ago, I think it is reasonable to bump the `peerDependency` to 7.
  - As of today the peer-dependency is defined as `>= 5.0.0`. I would advocate changing this to `^7`. The CI is not setup today to ensure that all the ESLint versions between 5 and 7 are compatible with this plugin. I would require updating the `peerDependency` value once ESLint 8 is released, which is fine as we would need to make sure the plugin is still compatible.
- Update minimal Node.js supported version to 12. #22 

## Minor changes
- Remove all the styles related rules from the config. Today all new SFDX projects come with prettier already installed. Enforcing styling-related rules is unnecessary IMO. 

## Nice to have
- Update remaining dev dependencies  #17
- Add proper testing for rules and configuration 
  - Use `mocha` (or some other test runner) to run the tests #18
  - Improve existing rules coverage
  - Add smoke test for configuration
- Run ESLint and Prettier as part of the CI #20
- Add missing documentation for `aura-service` rule

**Comment by trevor-bliss** [comment]
I would like to add 2 points:
- Remove non-public references
    - The `aura-service` rule is targeted at checking `.lib` files. Those are not available on the platform and Aura is no longer open source so this rule should be removed entirely.
    - Some [globals](https://github.com/forcedotcom/eslint-plugin-aura/blob/master/lib/index.js#L48) are references to an internal only testing utility. Remove these.
- Merge in rules from the `sfdx force:lightning:lint` command.

The 2nd bullet may be a non-trivial amount of work and could be tracked in a future release if necessary.

**Comment by trevor-bliss** [comment]
All of the above are now complete with the 2.0.0 release - https://github.com/forcedotcom/eslint-plugin-aura/releases/tag/v2.0.0
