### ISSUE TITLE
How can I configure this to ignore IE11?

### ISSUE THREAD

**Issue by JTScienceExchange** [forcedotcom/eslint-plugin-aura#36]
I see this repository depends on `eslint-plugin-compat` which allows us to specify which browsers to target. I am seeing a lot of errors in my js components dealing with IE11 issues. When I attempt to tell `eslint-plugin-compat` to only target chrome, this plugin still fails on IE11 issues.

**Comment by pmdartus** [comment]
You can override the list of targeted browsers by setting the `settings.targets` property in your ESLint config file. This property uses the [browserlist](https://browsersl.ist/) syntax.

In the following example, `eslint-plugin-compat` would only target the last 2 versions of Chrome: 

```json
{
    "plugins": ["@salesforce/eslint-plugin-aura"],
    "extends": [
      "plugin:@salesforce/eslint-plugin-aura/recommended",
      "plugin:@salesforce/eslint-plugin-aura/locker"
    ],

    "settings": {
        "targets":
          "last 2 Chrome versions"
    },
}
```
