### ISSUE TITLE
Documentation for the aura-service rule

### ISSUE THREAD

**Issue by touzoku** [forcedotcom/eslint-plugin-aura#7]
@rochejul could you please write the documentation to the rule?

[aura-service.md](https://github.com/forcedotcom/eslint-plugin-aura/blob/master/docs/rules/aura-service.md)

**Comment by rochejul** [comment]
Hi @touzoku 

Ok sure

**Comment by rochejul** [comment]
Naive question: do you want a PR?

**Comment by trevor-bliss** [comment]
Removing this rule in https://github.com/forcedotcom/eslint-plugin-aura/pull/24
